### ISSUE TITLE
Chemistry CSV file name column does not allow comma in the text

### ISSUE THREAD

**Issue by lulin-song** [hudsonriverlife/riverlife-sql#1]
The symbol comma ',' is used in the program as delimiter. The CSV file name column contains the symbol comma. It caused the issue.
@lzaima Please replace ',' with other symbol '/' or ':'  in name column in chemistry file.

**Comment by lzaima** [comment]
Is this for both years? I will change

**Comment by lzaima** [comment]
Fixed

**Comment by lulin-song** [comment]
() is not allowed either. 

> Is this for both years? I will change

Yes. () is not allowed either. comma is not allowed in the notes column too.

**Comment by lulin-song** [comment]
> () is not allowed either.
> 
> > Is this for both years? I will change
> 
> Yes. () is not allowed either. comma is not allowed in the notes column too.

You need check all the CVS files to make sure any text field does not have , or ().

**Comment by lzaima** [comment]
Fixed for all CSV files.
