### ISSUE TITLE
Fish.csv file issues

### ISSUE THREAD

**Issue by lulin-song** [hudsonriverlife/riverlife-sql#2]
1. 2017 Fish CSV file only contains one column. All data are filled in first column. I guess when you save the file without specifying delimiter. Can you create Fish cvs file with ',' comma as delimiter?
2. 2018 Fish CSV file one column seems not align.
<img width="487" alt="Screen Shot 2019-05-02 at 11 44 14 AM" src="https://user-images.githubusercontent.com/5776339/57088159-aabc2d80-6ccf-11e9-8c47-a13c3b9238ac.png">
@lzaima

**Comment by lzaima** [comment]
I don't understand what the issue is for 1. What is a "delimiter"

**Comment by lzaima** [comment]
#2 problem is fixed
